#!/bin/sh
# We run perl through a shell to avoid having to hard-code the path to perl
export LC_ALL=C
perl -e '$|=1;  $t=0; while(<>) { $t=int(`date +%s%N`)/1000; $ts = sprintf "%16d", $t; print $ts . " $_";}'
